export const LOADCHARACTERS = "LOADCHRACTERS";
export const LOADCHARACTERMOVIES = "LOADCHRACTERMOVIES";
export const LOADCHARACTERMOVIESSUCCESS = "LOADCHRACTERMOVIESSUCCESS";
export const LOADCHARACTERMOVIESFAIL = "LOADCHRLOADCHRACTERMOVIESFAIL";
export const CHANGEACTIVECHARACTER = "CHANGEACTIVECHRACTER";